-- Add Technology and Engineering subjects if they don't exist
INSERT OR IGNORE INTO subjects (name, description) VALUES
('Technology', 'Computer Science and Digital Skills'),
('Engineering', 'Engineering principles and problem-solving');

-- Create Technology Quizzes
INSERT INTO quizzes (subject_id, title, description, class, difficulty_level) VALUES
((SELECT id FROM subjects WHERE name = 'Technology'), 'Basic Programming', 'Introduction to programming concepts', '6', 'easy'),
((SELECT id FROM subjects WHERE name = 'Technology'), 'Web Development', 'Basics of web development and design', '6', 'medium'),
((SELECT id FROM subjects WHERE name = 'Technology'), 'Advanced Computing', 'Advanced computer science concepts', '6', 'hard');

-- Create Engineering Quizzes
INSERT INTO quizzes (subject_id, title, description, class, difficulty_level) VALUES
((SELECT id FROM subjects WHERE name = 'Engineering'), 'Engineering Basics', 'Basic engineering concepts', '6', 'easy'),
((SELECT id FROM subjects WHERE name = 'Engineering'), 'Mechanical Design', 'Introduction to mechanical engineering', '6', 'medium'),
((SELECT id FROM subjects WHERE name = 'Engineering'), 'Advanced Engineering', 'Complex engineering principles', '6', 'hard');

-- Technology Questions (Basic Programming)
INSERT INTO questions (quiz_id, question_text, options, correct_answer, difficulty_level, points, explanation) VALUES
((SELECT id FROM quizzes WHERE title = 'Basic Programming'), 'What is an algorithm?', '["A computer virus", "A step-by-step procedure to solve a problem", "A type of computer", "A programming language"]', 'A step-by-step procedure to solve a problem', 'easy', 1, 'An algorithm is a sequence of steps to solve a specific problem'),
((SELECT id FROM quizzes WHERE title = 'Basic Programming'), 'Which of these is a programming language?', '["Microsoft Word", "Python", "Google Chrome", "Windows"]', 'Python', 'easy', 1, 'Python is a popular programming language used for various applications'),
((SELECT id FROM quizzes WHERE title = 'Basic Programming'), 'What does CPU stand for?', '["Central Program Unit", "Central Processing Unit", "Computer Personal Unit", "Control Processing Unit"]', 'Central Processing Unit', 'easy', 1, 'CPU is the brain of the computer that processes instructions'),
((SELECT id FROM quizzes WHERE title = 'Basic Programming'), 'What is a variable in programming?', '["A type of computer", "A storage location with a name", "A computer game", "A website"]', 'A storage location with a name', 'easy', 1, 'Variables are used to store data in programming'),
((SELECT id FROM quizzes WHERE title = 'Basic Programming'), 'What is the purpose of a loop in programming?', '["To end a program", "To repeat certain actions", "To delete files", "To print text"]', 'To repeat certain actions', 'easy', 1, 'Loops are used to repeat a block of code multiple times'),
((SELECT id FROM quizzes WHERE title = 'Basic Programming'), 'What is debugging?', '["Creating a program", "Finding and fixing errors", "Running a program", "Writing code"]', 'Finding and fixing errors', 'easy', 1, 'Debugging is the process of identifying and fixing errors in code'),
((SELECT id FROM quizzes WHERE title = 'Basic Programming'), 'What is binary code?', '["A computer virus", "A system using only 0s and 1s", "A programming language", "A type of computer"]', 'A system using only 0s and 1s', 'easy', 1, 'Binary is the basic language of computers using only two digits'),
((SELECT id FROM quizzes WHERE title = 'Basic Programming'), 'What is an input device?', '["Monitor", "Printer", "Keyboard", "Speaker"]', 'Keyboard', 'easy', 1, 'Input devices like keyboards are used to enter data into a computer'),
((SELECT id FROM quizzes WHERE title = 'Basic Programming'), 'What does RAM stand for?', '["Random Access Memory", "Read Always Memory", "Run Automatic Memory", "Right Access Module"]', 'Random Access Memory', 'easy', 1, 'RAM is temporary memory used by computers to store working data'),
((SELECT id FROM quizzes WHERE title = 'Basic Programming'), 'What is a file extension?', '["A computer brand", "A type of computer", "Characters after dot in filename", "A programming language"]', 'Characters after dot in filename', 'easy', 1, 'File extensions indicate the type of file, like .txt or .doc');

-- Engineering Questions (Engineering Basics)
INSERT INTO questions (quiz_id, question_text, options, correct_answer, difficulty_level, points, explanation) VALUES
((SELECT id FROM quizzes WHERE title = 'Engineering Basics'), 'What is the basic principle of a lever?', '["Converting energy", "Multiplying force", "Storing data", "Generating electricity"]', 'Multiplying force', 'easy', 1, 'A lever is a simple machine that multiplies force through mechanical advantage'),
((SELECT id FROM quizzes WHERE title = 'Engineering Basics'), 'What does CAD stand for?', '["Computer Aided Design", "Computer Automatic Drawing", "Complex Art Design", "Computer Art Development"]', 'Computer Aided Design', 'easy', 1, 'CAD is used by engineers to create precise technical drawings'),
((SELECT id FROM quizzes WHERE title = 'Engineering Basics'), 'What is the purpose of a blueprint?', '["To paint buildings", "To provide construction details", "To decorate walls", "To measure temperature"]', 'To provide construction details', 'easy', 1, 'Blueprints are technical drawings that guide construction'),
((SELECT id FROM quizzes WHERE title = 'Engineering Basics'), 'Which tool is used to measure angles?', '["Ruler", "Protractor", "Scale", "Compass"]', 'Protractor', 'easy', 1, 'A protractor is used to measure and draw angles'),
((SELECT id FROM quizzes WHERE title = 'Engineering Basics'), 'What is the main purpose of a gear?', '["To store energy", "To transfer motion", "To generate heat", "To produce light"]', 'To transfer motion', 'easy', 1, 'Gears transfer rotational motion and can change speed or direction'),
((SELECT id FROM quizzes WHERE title = 'Engineering Basics'), 'What is the basic unit of force?', '["Watt", "Newton", "Volt", "Ampere"]', 'Newton', 'easy', 1, 'Newton (N) is the SI unit of force'),
((SELECT id FROM quizzes WHERE title = 'Engineering Basics'), 'What is the purpose of insulation?', '["To generate power", "To control temperature", "To increase weight", "To produce light"]', 'To control temperature', 'easy', 1, 'Insulation helps control heat transfer between materials'),
((SELECT id FROM quizzes WHERE title = 'Engineering Basics'), 'What is efficiency in engineering?', '["Speed of work", "Cost of project", "Useful output/total input ratio", "Size of machine"]', 'Useful output/total input ratio', 'easy', 1, 'Efficiency measures how well resources are converted to useful output'),
((SELECT id FROM quizzes WHERE title = 'Engineering Basics'), 'What is the purpose of a safety factor?', '["To make things cheaper", "To add extra margin of safety", "To increase speed", "To save energy"]', 'To add extra margin of safety', 'easy', 1, 'Safety factors ensure designs can handle more than expected loads'),
((SELECT id FROM quizzes WHERE title = 'Engineering Basics'), 'What is the main function of a pulley?', '["To store energy", "To lift loads easily", "To generate electricity", "To measure weight"]', 'To lift loads easily', 'easy', 1, 'Pulleys make it easier to lift heavy loads by changing force direction');

-- Add more advanced questions for Web Development and Advanced Computing
INSERT INTO questions (quiz_id, question_text, options, correct_answer, difficulty_level, points, explanation) VALUES
((SELECT id FROM quizzes WHERE title = 'Web Development'), 'What does HTML stand for?', '["High Text Markup Language", "Hyper Text Markup Language", "Hyper Transfer Markup Language", "High Transfer Markup Language"]', 'Hyper Text Markup Language', 'medium', 2, 'HTML is the standard markup language for creating web pages'),
((SELECT id FROM quizzes WHERE title = 'Web Development'), 'What is CSS used for?', '["Programming", "Styling web pages", "Database management", "Server configuration"]', 'Styling web pages', 'medium', 2, 'CSS controls the visual style and layout of web pages'),
((SELECT id FROM quizzes WHERE title = 'Web Development'), 'What is JavaScript primarily used for?', '["Database storage", "Web page styling", "Interactive functionality", "Server hosting"]', 'Interactive functionality', 'medium', 2, 'JavaScript adds interactivity to web pages'),
((SELECT id FROM quizzes WHERE title = 'Web Development'), 'What is a domain name?', '["A web browser", "A website address", "A programming language", "A computer part"]', 'A website address', 'medium', 2, 'Domain names are the addresses used to access websites'),
((SELECT id FROM quizzes WHERE title = 'Web Development'), 'What is responsive design?', '["Fast loading websites", "Adapting to screen sizes", "Colorful websites", "Complex programming"]', 'Adapting to screen sizes', 'medium', 2, 'Responsive design ensures websites work well on all devices'),
((SELECT id FROM quizzes WHERE title = 'Web Development'), 'What is the purpose of SQL?', '["Web design", "Programming", "Database management", "Graphics design"]', 'Database management', 'medium', 2, 'SQL is used to manage and query databases'),
((SELECT id FROM quizzes WHERE title = 'Web Development'), 'What is a web server?', '["A computer program", "A website", "A computer hosting websites", "A browser"]', 'A computer hosting websites', 'medium', 2, 'Web servers store and deliver web content'),
((SELECT id FROM quizzes WHERE title = 'Web Development'), 'What is HTTP?', '["A programming language", "A transfer protocol", "A web browser", "A computer part"]', 'A transfer protocol', 'medium', 2, 'HTTP is the protocol for transferring data on the web'),
((SELECT id FROM quizzes WHERE title = 'Web Development'), 'What is a cookie in web terms?', '["A snack", "A website", "A data file stored on computer", "A program"]', 'A data file stored on computer', 'medium', 2, 'Cookies store user data for websites'),
((SELECT id FROM quizzes WHERE title = 'Web Development'), 'What is DNS?', '["A web browser", "Domain name system", "A programming language", "A computer part"]', 'Domain name system', 'medium', 2, 'DNS converts domain names to IP addresses');

-- Advanced Computing Questions
INSERT INTO questions (quiz_id, question_text, options, correct_answer, difficulty_level, points, explanation) VALUES
((SELECT id FROM quizzes WHERE title = 'Advanced Computing'), 'What is machine learning?', '["Computer repair", "AI system learning from data", "Fast computing", "Computer programming"]', 'AI system learning from data', 'hard', 3, 'Machine learning allows systems to learn from experience'),
((SELECT id FROM quizzes WHERE title = 'Advanced Computing'), 'What is cloud computing?', '["Weather forecasting", "Internet services", "Remote computing services", "Computer networking"]', 'Remote computing services', 'hard', 3, 'Cloud computing provides services over the internet'),
((SELECT id FROM quizzes WHERE title = 'Advanced Computing'), 'What is cybersecurity?', '["Computer speed", "Internet safety", "Protecting computer systems", "Programming"]', 'Protecting computer systems', 'hard', 3, 'Cybersecurity protects systems from digital attacks'),
((SELECT id FROM quizzes WHERE title = 'Advanced Computing'), 'What is an API?', '["A computer part", "Programming interface", "A website", "A computer brand"]', 'Programming interface', 'hard', 3, 'APIs allow different software to communicate'),
((SELECT id FROM quizzes WHERE title = 'Advanced Computing'), 'What is blockchain?', '["A computer part", "A chain of blocks", "Distributed ledger technology", "A programming language"]', 'Distributed ledger technology', 'hard', 3, 'Blockchain is a secure, decentralized record-keeping technology'),
((SELECT id FROM quizzes WHERE title = 'Advanced Computing'), 'What is quantum computing?', '["Fast computers", "Computing using quantum mechanics", "Large computers", "New computers"]', 'Computing using quantum mechanics', 'hard', 3, 'Quantum computing uses quantum phenomena for calculations'),
((SELECT id FROM quizzes WHERE title = 'Advanced Computing'), 'What is big data?', '["Large files", "Complex databases", "Massive data analysis", "Computer storage"]', 'Massive data analysis', 'hard', 3, 'Big data involves analyzing extremely large data sets'),
((SELECT id FROM quizzes WHERE title = 'Advanced Computing'), 'What is virtualization?', '["Virtual reality", "Creating virtual resources", "Computer games", "3D graphics"]', 'Creating virtual resources', 'hard', 3, 'Virtualization creates virtual versions of computing resources'),
((SELECT id FROM quizzes WHERE title = 'Advanced Computing'), 'What is edge computing?', '["Sharp computers", "Local data processing", "Internet computing", "Fast computing"]', 'Local data processing', 'hard', 3, 'Edge computing processes data near its source'),
((SELECT id FROM quizzes WHERE title = 'Advanced Computing'), 'What is DevOps?', '["Development options", "Development operations", "Device operations", "Digital options"]', 'Development operations', 'hard', 3, 'DevOps combines development and IT operations');

-- Add advanced Engineering questions (Mechanical Design and Advanced Engineering)
INSERT INTO questions (quiz_id, question_text, options, correct_answer, difficulty_level, points, explanation) VALUES
((SELECT id FROM quizzes WHERE title = 'Mechanical Design'), 'What is stress analysis?', '["Psychological testing", "Material strength study", "Stress management", "Design planning"]', 'Material strength study', 'medium', 2, 'Stress analysis examines how forces affect materials'),
((SELECT id FROM quizzes WHERE title = 'Mechanical Design'), 'What is thermodynamics?', '["Temperature study", "Heat and energy study", "Weather study", "Material study"]', 'Heat and energy study', 'medium', 2, 'Thermodynamics studies heat and energy relationships'),
((SELECT id FROM quizzes WHERE title = 'Mechanical Design'), 'What is fluid dynamics?', '["Water study", "Liquid movement study", "Flow behavior study", "Ocean study"]', 'Flow behavior study', 'medium', 2, 'Fluid dynamics studies how fluids behave when in motion'),
((SELECT id FROM quizzes WHERE title = 'Mechanical Design'), 'What is CAM in engineering?', '["Camera technology", "Computer-Aided Manufacturing", "Computer Animation", "Design software"]', 'Computer-Aided Manufacturing', 'medium', 2, 'CAM uses computers to control manufacturing processes'),
((SELECT id FROM quizzes WHERE title = 'Mechanical Design'), 'What is tolerance in engineering?', '["Patience", "Acceptable variation", "Material strength", "Design feature"]', 'Acceptable variation', 'medium', 2, 'Tolerance is the acceptable variation in dimensions'),
((SELECT id FROM quizzes WHERE title = 'Mechanical Design'), 'What is torque?', '["Speed measure", "Rotational force", "Power measure", "Energy type"]', 'Rotational force', 'medium', 2, 'Torque is a measure of rotational force'),
((SELECT id FROM quizzes WHERE title = 'Mechanical Design'), 'What is friction?', '["Material property", "Resistance to motion", "Heat generation", "Surface texture"]', 'Resistance to motion', 'medium', 2, 'Friction is the force resisting motion between surfaces'),
((SELECT id FROM quizzes WHERE title = 'Mechanical Design'), 'What is a prototype?', '["Final product", "Preliminary version", "Design drawing", "Machine part"]', 'Preliminary version', 'medium', 2, 'A prototype is an early sample or model of a product'),
((SELECT id FROM quizzes WHERE title = 'Mechanical Design'), 'What is tensile strength?', '["Material weight", "Resistance to pulling", "Material hardness", "Material density"]', 'Resistance to pulling', 'medium', 2, 'Tensile strength measures resistance to being pulled apart'),
((SELECT id FROM quizzes WHERE title = 'Mechanical Design'), 'What is mechanical advantage?', '["Force multiplication", "Speed increase", "Power boost", "Energy saving"]', 'Force multiplication', 'medium', 2, 'Mechanical advantage is the force multiplication by a machine');