// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcbhagyfvszuyshoeiya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjYmhhZ3lmdnN6dXlzaG9laXlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MzM2NDEsImV4cCI6MjA3NDEwOTY0MX0.fq4smaoGK13shylivEfZ8atZ2ZPbwXxSfWD5-1cen4Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});